### PR TITLE
add support for table, table_row, table_header, table_cell

### PR DESCRIPTION
**Pull request by sauerbraten**
not sure if the way I pass attributes in the `tag()` method is the best we can do. let me know if I should handle attrs more generally in `renderOpeningTag()` :)

### CODE REVIEW

**Comment by sauerbraten** [comment]
@hanspagel what about this one? did you unsubscribe from notifications on your own repo? ;)

**Comment by hanspagel** [comment]
Thanks for the PR and sorry for the delay!

**Comment by hanspagel** [comment]
Tagged as 0.7.1

**Comment by sauerbraten** [comment]
Oh no worries, I was just wondering what was up with this repo when you were so super fast in the other! Thanks a lot for the package, it's a joy to work with!

**Pull request merged**
